### ISSUE TITLE
String containing \n throws SyntaxError: Unterminated string literal

### ISSUE THREAD

**Issue by MaxMilton** [meriyah/meriyah#191]
When parsing any code which includes a string containing a terminated new line `\n` the parser throws "SyntaxError: Unterminated string literal".

Minimal repro:

```js
require('meriyah').parse('var str = "\n"');
```

Versions:

- meriyah: `v4.1.5`
- node: `12`, `14`, `16` (same error on all support node versions)
- OS: `Linux max 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux`

Stack trace:

```
❱ node -e "require('meriyah').parse('var str = \"\n\"');"

/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:187
    throw new ParseError(parser.index, parser.line, parser.column, type, ...params);
    ^

SyntaxError: [1:11]: Unterminated string literal
    at report (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:187:11)
    at scanString (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:940:5)
    at scanSingleToken (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:1766:28)
    at nextToken (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:1716:20)
    at parseVariableDeclaration (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:5354:9)
    at parseVariableDeclarationList (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:5339:19)
    at parseVariableStatement (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:5329:26)
    at parseStatement (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:4882:20)
    at parseStatementListItem (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:4876:20)
    at parseStatementList (/home/max/Projects/packages/esbuild-minify-templates/node_modules/meriyah/dist/meriyah.cjs:4811:25) {
  index: 11,
  line: 1,
  column: 11,
  description: '[1:11]: Unterminated string literal',
  loc: { line: 1, column: 11 }
}
```

**Comment by 3cp** [comment]
`'var str = "\n"'` literally means:
```
var str = "
"
```

It failed because double quoted string in JS doesn't support multiline.

what you wanted is `'var str = "\\n"'`, you need to escape `\` when writing it inside JS `'string'`.

**Comment by MaxMilton** [comment]
That makes sense and it's rather obvious in hindsight. After writing 100+ unit tests my head was a bit of a mess and its a funny mistake!

Thank you for getting back to this, I appreciate it :)

**Comment by lazarljubenovic** [comment]
The little-known [`String.raw`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) tag helps a lot when dealing with "nested" escapes, especially with unit tests.
