### ISSUE TITLE
[Typescript Error]: Function declaration must have a name in this context

### ISSUE THREAD

**Issue by felipelealdefaria** [meriyah/meriyah#196]
Hi, I'm working on a project where I need to convert snippets of code to AST. I have two simple examples of functions using Typescript:

```typescript
export const arrowFunction = (value: any): string => {
  const { type } = value
  return type
}

export function regularFunction (value: any): string {
  // this is a regular function
  const { type } = value
  return type
}
```

For the case of **regularFunction** I don't have any problem, but when I use the parse function in **arrowFunction** I get the error below:

```
<rootDir>/node_modules/meriyah/dist/meriyah.cjs:187
    throw new ParseError(parser.index, parser.line, parser.column, type, ...params);
    ^

ParseError [SyntaxError]: [1:10]: Function declaration must have a name in this context
    at report (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:187:11)
    at parseFunctionDeclaration (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:6592:13)
    at parseStatementListItem (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:4853:20)
    at parseModuleItem (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:4840:26)
    at parseModuleItemList (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:4825:25)
    at parseSource (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:4769:16)
    at Object.parseModule (<rootDir>/node_modules/meriyah/dist/meriyah.cjs:8780:12)
    at parse (<rootDir>/node_modules/abstract-syntax-tree/src/parse.js:4:18)
    at parse (<rootDir>/node_modules/abstract-syntax-tree/index.js:75:12)
    at Object.<anonymous> (<rootDir>/dist/clones/arrow-and-regular/index.js:10:43) {
  index: 10,
  line: 1,
  column: 10,
  description: '[1:10]: Function declaration must have a name in this context',
  loc: { line: 1, column: 10 }
}
```

I realized that it can be related to the newer syntaxes of the language and remembering that I only have this error when using Typescript.

|                                    Library                                       |    Version    |
|----------------------------------------------------------------------------------|:-------------:|
| meriyah | ^4.1.5 |
|typescript | ^4.2.3 |

**Comment by 3cp** [comment]
FYI meriyah doesn't understand TypeScript syntax, only JavaScript.

**Comment by 3cp** [comment]
TypeScript compiler itself can parse ts code, but not in Estree AST.

If you want a TypeScript parser with output close to Estree AST, there are two well-used parsers that I know:

1. eslint's TypeScript parser
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser

2. babel parser with typescript extension, you also need the estree plugin to make the output more like Estree.
https://babeljs.io/docs/en/babel-parser/

**Comment by felipelealdefaria** [comment]
Thank you very much @3cp! This information will help me a lot in my project.
