### ISSUE TITLE
Syntax error on valid javascript code

### ISSUE THREAD

**Issue by jpike88** [meriyah/meriyah#5]
```
{ SyntaxError: Invalid left-hand side in assignment (64:39)
        if (async === void 0) { async = false; }
                                       ^

 at report (/a/node_modules/fuse-box/transform/meriyah.js:168:11)
    at parseAssignmentExpression (/a/node_modules/fuse-box/transform/meriyah.js:2635:13)
    at parseAsyncArrowOrAsyncFunctionDeclaration (/a/node_modules/fuse-box/transform/meriyah.js:1987:12)
    at parseStatementListItem (/a/node_modules/fuse-box/transform/meriyah.js:1813:20)
    at parseBlock (/a/node_modules/fuse-box/transform/meriyah.js:1908:19)
    at parseStatement (/a/node_modules/fuse-box/transform/meriyah.js:1821:20)
    at parseConsequentOrAlternate (/a/node_modules/fuse-box/transform/meriyah.js:2040:11)
    at parseIfStatement (/a/node_modules/fuse-box/transform/meriyah.js:2025:24)
    at parseStatement (/a/node_modules/fuse-box/transform/meriyah.js:1827:20)
    at parseStatementListItem (/a/node_modules/fuse-box/transform/meriyah.js:1815:20)
```

**Comment by jpike88** [comment]
https://raw.githubusercontent.com/ag-grid/ag-grid/master/dist/ag-grid-community.js

This file contains those lines

**Comment by KFlash** [comment]
Thanx for this :) I'm actually in the middle of fuzz testing the source so will fix it shortly!

**Comment by jpike88** [comment]
Thanks, I'm working closely with the fuse-box project, apparently this library totally kicks ass so keep up the good work :)

**Comment by KFlash** [comment]
The issue was that "async" isn't seen as a "ordinary" ident so I just forgot to make async ident assignable :)

Fix is coming within a few minutes

**Comment by jpike88** [comment]
Thanks, I understand @nchanged is getting a custom build from you, should that sit on a branch here? Or is it too weird

**Comment by nchanged** [comment]
@KFlash can't wait for the build

**Comment by KFlash** [comment]
I just got home. Will fix you a build soon.

**Comment by KFlash** [comment]
@jpike88 I keep customs on my HDD :) And just delivered a new custom build to @nchanged

**Comment by KFlash** [comment]
@jpike88 @nchanged No more need for custom builds. See https://github.com/meriyah/meriyah/issues/2
