### ISSUE TITLE
Block body arrows can not be immediately invoked without a group

### ISSUE THREAD

**Issue by SephReed** [meriyah/meriyah#62]
The following code will throw an error:

```
const a = () => { alert("hi") }

(a && a()) || alert("howdy");
```

It appears to think that `(a && a())` is trying to invoke the function.

```
SyntaxError: [29:1]: Block body arrows can not be immediately invoked without a group
    at report (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:188:13)
    at parseArrowFunctionExpression (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:5511:19)
    at parseParenthesizedArrow (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:5484:14)
    at parseParenthesizedExpression (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:5310:18)
    at parsePrimaryExpression (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:4062:22)
    at parseExpression (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:3522:18)
    at parseAssignmentExpression (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:3552:25)
    at parseExpressionOrLabelledStatement (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:2654:14)
    at parseStatement (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:2633:22)
    at parseStatementListItem (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/meriyah/dist/meriyah.umd.js:2583:22)
```

**Comment by nchanged** [comment]
On buntis
https://github.com/buntis/buntis/issues/42

```
const foo = () => {}

(a && b)|| 1
```

https://github.com/fuse-box/fuse-box/issues/1732

**Comment by SephReed** [comment]
Good find

**Comment by KFlash** [comment]
Still RL issues, so asked someone to fix it. It's solved so closing

**Comment by 3cp** [comment]
@KFlash this issue is not fixed.

```js
const a = (v) => { console.log('hello ' + v) }
('world');
```

meriyah thinks it's one statement `const a = (the_func)('world')`;
While both browser and nodejs thinks that is two statements.

**Comment by KFlash** [comment]
@3cp Could you try a pr?

**Comment by 3cp** [comment]
Thx! Fixed in 1.9.12.

**Comment by 3cp** [comment]
I see you fixed seafox too!

**Comment by KFlash** [comment]
I tried to find a solution first on Seafox, then I copied the solution to Meriyah. Now I'm working on an incremental parser
